### ISSUE TITLE
全体管理

### ISSUE THREAD

**Issue by hide-a1** [camp-team/team-arima#1]
## MTG
- [x] 第３回事前MTG（2020.11.3 14:00 start）
- [ ] キックオフMTG（2020.11.7 10:00 start)
### 事前準備
- [x] 要件定義・設計 @hide-a1 
- [x] issueを立てる #10  @hide-a1 
- [x] XDプロトタイプ作成 #9  @hide-a1 
- [x] Firebase作成 #12  @hide-a1 
- [x] プロダクト名を考える #13  @hide-a1  @chamaboy  @K-Yuki1019 @kaikai02   

### 環境構築
- [x] AngularInit #2 @hide-a1 
- [x] AngularMaterial #2  @hide-a1 
- [x] firebaseInit
- [x] AngularFire #2  @hide-a1 
- [ ] 自動Prettier #2  @hide-a1 
- [ ] 自動deploy #3  @hide-a1 

### 画面作成
- [ ] 共通画面：ヘッダー作成 #4 
- [ ] 共通画面：フッター作成(オプション） #5 
- [ ] LP画面 #7 @kaikai02 
- [ ] プロフィール画面 #24 @chamaboy 
- [ ] ホーム画面 #14 
- [ ] 個人ページ画面 #15 
- [ ] フォーム画面 #25 @hide-a1 
- [ ] 検索画面 #26 @K-Yuki1019 
- [ ] カードコンポーネント #22
- [ ] カレンダーコンポーネント #23 @hide-a1 
- [ ] 404 #28
- [ ] PC対応 #29
### 機能実装
- [ ] 機能実装：ログイン・ログアウト #6 @chamaboy 
- [ ] 機能実装：投稿 #16 @hide-a1 
- [ ] 機能実装：いいね #17 @chamaboy 
- [ ] 機能実装：検索 #18 @K-Yuki1019 
- [ ] 機能実装：投稿出力 #27 @hide-a1 
- [ ] 機能実装：編集・削除 #19
- [ ] 機能実装：ユーザー退会 #20
- [ ] 機能実装：プロフィール編集 #21 @chamaboy
- [ ] 機能実装：冪等 
## 設計
![image](https://user-images.githubusercontent.com/60844124/97984678-69539380-1e1a-11eb-80eb-2a78b371087b.png)

## プロトタイプ
LP
https://xd.adobe.com/view/5e9ac3cc-b5f1-4ac8-9c02-f58885ac4238-0bc9/screen/cc1f193c-2adb-4227-bb0f-57129cb04bda
コンテンツ
https://xd.adobe.com/view/3dbbce47-1caf-441b-be3d-55cba8e8788b-68e8/
